backend:
  # Use netlify identity as backend
  branch: master
  ### enable below lines for github integration ###
  name: github
  repo: foundations-design/janemilym
media_folder: "site/static/img"
public_folder: "/img"
  


# Theme
# Content
#   Site Settings
#   Social Links
#     - Show on Homepage Toggle
#   Music

#   Live
#     - Create True


# Please run "npx netlify-cms-proxy-server" for local backend
# Requires Netlify Config at "Site Configuration -> Build & Deploy -> Deploy Notifications"
local_backend: true
publish_mode: editorial_workflow
collections:
  - name: "theme"
    label: "Theme"
    files: 
      - file: "site/_data/theme.yaml"
        name: "Theme"
        label: "Theme"
        fields: 
          - {label: "Sidebar Color", name: "sidebarColor", widget: "color", allowInput: true, hint: "Accepts color in any HTML-friendly format, including [color names (link)](https://www.w3schools.com/tags/ref_colornames.asp)"}
          - {label: "Header Color", name: "headingColor", widget: "color", allowInput: true, hint: "Accepts color in any HTML-friendly format, including [color names (link)](https://www.w3schools.com/tags/ref_colornames.asp)"}
  - name: "content" # Used in routes, e.g., /admin/collections/resume
    label: "Content" # Used in the UI
    # folder: "_resume" # The path to the folder where the documents are stored
    # create: true # Allow users to create new documents in this collection
    files: # The fields for each document, usually in front matter
      - name: "site"
        label: "Site Settings (Name, Title, Profile Picture)"
        file: "site/_data/site.yaml"
        fields: 
          - {label: "Name", name: "name", widget: "string", required: false}
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Profile Picture", name: "pic", widget: "image", required: false}
      - name: "social"
        label: "Social Links"
        file: "site/_data/social.yaml"
        fields:
          - label: "Social Links"
            name: "links"
            widget: "list"
            fields:
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Icon"
                name: "image"
                widget: "image"
                media_library:
                  config:
                    multiple: false
      - name: "music"
        label: "Music"
        file: "site/_data/music.yaml"
        create: true
        fields:
          - label: Records
            name: record
            widget: "list"
            fields:
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Album Art"
                name: "album_art"
                widget: "image"
                media_library:
                  config:
                    multiple: false
      - name: "live"
        label: "Live"
        file: "site/_data/live.yaml"
        create: true
        fields:
          - label: Live Sets
            name: sets
            widget: "list"
            fields:
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Date"
                name: "date"
                widget: "datetime"
              - label: "Location"
                name: "location"
                widget: "string"
  - name: "project"
    label: "Projects"
    folder: "site/projects"
    create: true
    fields:
      - {label: "Profile Picture", name: "pic", widget: "image", required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "body", widget: "string"}